"""Generate simple text responses in various styles."""

import os
from typing import Any

try:  # optional OpenAI usage
    import openai  # type: ignore
except Exception:  # pragma: no cover - optional dependency
    openai = None  # type: ignore


def generate_response(context: Any, style: str) -> str:
    """Return a short message using the desired style.

    If the ``openai`` package and an ``OPENAI_API_KEY`` environment variable are
    available, the response will be generated by the ChatGPT API. Otherwise a
    simple placeholder string is returned.
    """
    if not isinstance(context, str):
        context = str(context)
    if not isinstance(style, str):
        style = str(style)

    api_key = os.environ.get("OPENAI_API_KEY")
    if openai and api_key:
        openai.api_key = api_key
        try:
            resp = openai.ChatCompletion.create(
                model="gpt-3.5-turbo",
                messages=[
                    {
                        "role": "system",
                        "content": f"Reply in a {style} sales style.",
                    },
                    {"role": "user", "content": context},
                ],
                temperature=0.5,
            )
            return resp.choices[0].message.content.strip()
        except Exception:
            # On any error fall back to simple output
            pass

    return f"This is a {style} style message for context: {context}"

